import { Recipe } from './types';

export const seedRecipes: Recipe[] = [
  {
    id: 'seed-levelsio-airfryer-steak',
    title: 'Frozen Steak & Veggies (Air Fryer)',
    description:
      'The laziest good meal you\'ll ever make. Frozen steak, frozen potatoes, frozen broccoli — straight into the air fryer. 30 seconds of actual work. Via @levelsio.',
    ingredients: [
      '1 frozen free-range steak (ribeye or NY strip, ~8-10oz)',
      '1 cup frozen organic baby potatoes',
      '1 cup frozen organic broccoli florets',
      'Olive oil spray, ghee, butter, or lard',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Place frozen steak, frozen potatoes, and frozen broccoli in the Ninja Crispi Pro basket. No thawing needed.',
      'Spray everything with olive oil or add small pats of ghee/butter/lard on top.',
      'Season with salt and pepper.',
      'Set to Air Crisp at 360°F. Cook for 10 minutes.',
      'Flip the steak and toss the veggies. Cook for another 10 minutes.',
      'Check steak temp — 130°F for medium-rare, 140°F for medium. Add 2-3 minutes if needed.',
      'Let steak rest 3 minutes before cutting. Serve.',
    ],
    photoUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    servings: '1',
    cookTime: '20 min',
    prepTime: '30 sec',
    totalTimeMinutes: 20,
    sourceUrl: 'https://x.com/levelsio',
    videoUrl: '',
    proteinType: 'beef',
    cookingMethod: 'air-fryer',
    nutrition: {
      calories: 580,
      protein: 48,
      carbs: 28,
      fat: 30,
      perServing: true,
    },
    createdAt: '2026-02-08T23:50:00Z',
    updatedAt: '2026-02-08T23:50:00Z',
  },
  {
    id: 'seed-nyt-chicken-enchiladas',
    title: 'Chicken Enchiladas',
    description:
      'Rick Martínez\'s 5-star NYT classic. Rotisserie chicken + canned enchilada sauce = ready in about an hour. 4,283 ratings can\'t be wrong. American Southwest-inspired, dead simple, freezes beautifully.',
    ingredients: [
      '¼ cup vegetable oil',
      '12 (6-inch) corn tortillas',
      '½ medium white onion, chopped',
      '1 medium poblano or green bell pepper, stemmed, seeded and chopped',
      '3 garlic cloves, finely chopped',
      '2 large tomatoes, cored and finely chopped',
      'Kosher salt (Diamond Crystal)',
      '2 cups cooked shredded chicken (rotisserie chicken works great)',
      '2½ cups enchilada sauce (or 2 x 10oz cans)',
      '12 oz (3 cups) sharp Cheddar, shredded',
      'Pico de gallo, for serving (optional)',
    ],
    instructions: [
      'Heat oven to 400°F. Using 2 tbsp of the oil, lightly brush both sides of each tortilla. Heat a large skillet or griddle over medium-high and, working in batches, cook tortillas until lightly browned and just starting to crisp but still pliable, 45 seconds to 1 minute per side. Set aside.',
      'Heat the remaining 2 tbsp oil in a large skillet over medium-high. Cook onion, poblano, garlic, tomatoes and juices, and 1 tsp salt, stirring and scraping up browned bits, until most liquid has evaporated and tomatoes begin to stick, 9–11 minutes.',
      'Stir in chicken, ½ cup enchilada sauce, and ½ tsp salt until combined and warmed through. Remove from heat. Taste and season.',
      'Pour ½ cup enchilada sauce into a 9x13-inch baking dish, spreading to cover the bottom.',
      'Working one at a time, place a scant ¼ cup of chicken filling down the center of each tortilla, roll to secure, and place seam side down in the dish. Nestle them tightly together.',
      'Pour remaining enchilada sauce over the tortillas. Scatter cheese on top.',
      'Bake until sauce is bubbling and cheese is beginning to brown, 15–20 minutes.',
      'Serve warm topped with pico de gallo. For leftovers: wrap portions of 2–3 enchiladas in plastic wrap or freezer bag. Freezes up to 3 months.',
    ],
    photoUrl: 'https://images.unsplash.com/photo-1534352956036-cd81e27dd615?w=800&q=80',
    servings: '6',
    cookTime: '55 min',
    prepTime: '10 min',
    totalTimeMinutes: 65,
    sourceUrl: 'https://cooking.nytimes.com/recipes/1024636-chicken-enchiladas',
    videoUrl: '',
    proteinType: 'chicken',
    cookingMethod: 'oven',
    nutrition: {
      calories: 450,
      protein: 28,
      carbs: 30,
      fat: 24,
      perServing: true,
    },
    airFryerAlt: {
      ingredients: [
        '2 tbsp vegetable oil',
        '8 (6-inch) corn tortillas',
        '½ medium white onion, chopped',
        '1 medium poblano or green bell pepper, stemmed, seeded and chopped',
        '3 garlic cloves, finely chopped',
        '2 large tomatoes, cored and finely chopped',
        'Kosher salt (Diamond Crystal)',
        '2 cups cooked shredded chicken (rotisserie chicken works great)',
        '2 cups enchilada sauce (or ~1.5 x 10oz cans)',
        '8 oz (2 cups) sharp Cheddar, shredded',
        'Pico de gallo, for serving (optional)',
      ],
      instructions: [
        'Brush tortillas lightly with oil on both sides. Working in batches, air crisp at 350°F in your Ninja Crispi Pro for 1–2 minutes per side until pliable and lightly browned. Set aside.',
        'Cook the filling on the stovetop as normal: sauté onion, poblano, garlic, tomatoes with 1 tsp salt in a skillet over medium-high, 9–11 minutes. Stir in chicken, ½ cup sauce, ½ tsp salt.',
        'Spoon a thin layer of enchilada sauce into an air fryer-safe baking dish or pan that fits your Ninja Crispi Pro (a 7–8" round or square dish works).',
        'Fill and roll tortillas, placing seam side down. You\'ll need to work in 2 batches of 4 enchiladas.',
        'Pour sauce over the batch, top with cheese.',
        'Air Crisp at 375°F for 8–10 minutes until cheese is bubbly and golden.',
        'Repeat with second batch. Serve with pico de gallo.',
      ],
      cookTime: '20 min (2 batches × 10 min)',
      prepTime: '10 min',
      totalTimeMinutes: 40,
      notes: 'Scaled to 8 tortillas to fit the Ninja Crispi Pro in 2 batches. Cook the filling on the stovetop as usual — the air fryer handles the baking step. Faster overall (40 min vs 65 min) and you get crispier cheese edges.',
    },
    createdAt: '2026-02-08T23:57:00Z',
    updatedAt: '2026-02-08T23:57:00Z',
  },
];
