import { Recipe } from './types';

export const seedRecipes: Recipe[] = [
  {
    id: 'seed-levelsio-airfryer-steak',
    title: 'Frozen Steak & Veggies (Air Fryer)',
    description:
      'The laziest good meal you\'ll ever make. Frozen steak, frozen potatoes, frozen broccoli — straight into the air fryer. 30 seconds of actual work. Via @levelsio.',
    ingredients: [
      '1 frozen free-range steak (ribeye or NY strip, ~8-10oz)',
      '1 cup frozen organic baby potatoes',
      '1 cup frozen organic broccoli florets',
      'Olive oil spray, ghee, butter, or lard',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Place frozen steak, frozen potatoes, and frozen broccoli in the Ninja Crispi Pro basket. No thawing needed.',
      'Spray everything with olive oil or add small pats of ghee/butter/lard on top.',
      'Season with salt and pepper.',
      'Set to Air Crisp at 360°F. Cook for 10 minutes.',
      'Flip the steak and toss the veggies. Cook for another 10 minutes.',
      'Check steak temp — 130°F for medium-rare, 140°F for medium. Add 2-3 minutes if needed.',
      'Let steak rest 3 minutes before cutting. Serve.',
    ],
    photoUrl: '/recipes/frozen-steak-airfryer.jpg',
    servings: '1',
    cookTime: '20 min',
    prepTime: '30 sec',
    totalTimeMinutes: 20,
    sourceUrl: 'https://x.com/levelsio',
    videoUrl: '',
    proteinType: 'beef',
    cookingMethod: 'air-fryer',
    nutrition: {
      calories: 580,
      protein: 48,
      carbs: 28,
      fat: 30,
      perServing: true,
    },
    createdAt: '2026-02-08T23:50:00Z',
    updatedAt: '2026-02-08T23:50:00Z',
  },
  {
    id: 'seed-nyt-chicken-enchiladas',
    title: 'Chicken Enchiladas',
    description:
      'Rick Martínez\'s 5-star NYT classic. Rotisserie chicken + canned enchilada sauce = ready in about an hour. 4,283 ratings can\'t be wrong. American Southwest-inspired, dead simple, freezes beautifully.',
    ingredients: [
      '¼ cup vegetable oil',
      '12 (6-inch) corn tortillas',
      '½ medium white onion, chopped',
      '1 medium poblano or green bell pepper, stemmed, seeded and chopped',
      '3 garlic cloves, finely chopped',
      '2 large tomatoes, cored and finely chopped',
      'Kosher salt (Diamond Crystal)',
      '2 cups cooked shredded chicken (rotisserie chicken works great)',
      '2½ cups enchilada sauce (or 2 x 10oz cans)',
      '12 oz (3 cups) sharp Cheddar, shredded',
      'Pico de gallo, for serving (optional)',
    ],
    instructions: [
      'Heat oven to 400°F. Using 2 tbsp of the oil, lightly brush both sides of each tortilla. Heat a large skillet or griddle over medium-high and, working in batches, cook tortillas until lightly browned and just starting to crisp but still pliable, 45 seconds to 1 minute per side. Set aside.',
      'Heat the remaining 2 tbsp oil in a large skillet over medium-high. Cook onion, poblano, garlic, tomatoes and juices, and 1 tsp salt, stirring and scraping up browned bits, until most liquid has evaporated and tomatoes begin to stick, 9–11 minutes.',
      'Stir in chicken, ½ cup enchilada sauce, and ½ tsp salt until combined and warmed through. Remove from heat. Taste and season.',
      'Pour ½ cup enchilada sauce into a 9x13-inch baking dish, spreading to cover the bottom.',
      'Working one at a time, place a scant ¼ cup of chicken filling down the center of each tortilla, roll to secure, and place seam side down in the dish. Nestle them tightly together.',
      'Pour remaining enchilada sauce over the tortillas. Scatter cheese on top.',
      'Bake until sauce is bubbling and cheese is beginning to brown, 15–20 minutes.',
      'Serve warm topped with pico de gallo. For leftovers: wrap portions of 2–3 enchiladas in plastic wrap or freezer bag. Freezes up to 3 months.',
    ],
    photoUrl: '/recipes/chicken-enchiladas.jpg',
    servings: '6',
    cookTime: '55 min',
    prepTime: '10 min',
    totalTimeMinutes: 65,
    sourceUrl: 'https://cooking.nytimes.com/recipes/1024636-chicken-enchiladas',
    videoUrl: '',
    proteinType: 'chicken',
    cookingMethod: 'oven',
    nutrition: {
      calories: 450,
      protein: 28,
      carbs: 30,
      fat: 24,
      perServing: true,
    },
    airFryerAlt: {
      ingredients: [
        '2 tbsp vegetable oil',
        '8 (6-inch) corn tortillas',
        '½ medium white onion, chopped',
        '1 medium poblano or green bell pepper, stemmed, seeded and chopped',
        '3 garlic cloves, finely chopped',
        '2 large tomatoes, cored and finely chopped',
        'Kosher salt (Diamond Crystal)',
        '2 cups cooked shredded chicken (rotisserie chicken works great)',
        '2 cups enchilada sauce (or ~1.5 x 10oz cans)',
        '8 oz (2 cups) sharp Cheddar, shredded',
        'Pico de gallo, for serving (optional)',
      ],
      instructions: [
        'Brush tortillas lightly with oil on both sides. Working in batches, air crisp at 350°F in your Ninja Crispi Pro for 1–2 minutes per side until pliable and lightly browned. Set aside.',
        'Cook the filling on the stovetop as normal: sauté onion, poblano, garlic, tomatoes with 1 tsp salt in a skillet over medium-high, 9–11 minutes. Stir in chicken, ½ cup sauce, ½ tsp salt.',
        'Spoon a thin layer of enchilada sauce into an air fryer-safe baking dish or pan that fits your Ninja Crispi Pro (a 7–8" round or square dish works).',
        'Fill and roll tortillas, placing seam side down. You\'ll need to work in 2 batches of 4 enchiladas.',
        'Pour sauce over the batch, top with cheese.',
        'Air Crisp at 375°F for 8–10 minutes until cheese is bubbly and golden.',
        'Repeat with second batch. Serve with pico de gallo.',
      ],
      cookTime: '20 min (2 batches × 10 min)',
      prepTime: '10 min',
      totalTimeMinutes: 40,
      notes: 'Scaled to 8 tortillas to fit the Ninja Crispi Pro in 2 batches. Cook the filling on the stovetop as usual — the air fryer handles the baking step. Faster overall (40 min vs 65 min) and you get crispier cheese edges.',
    },
    createdAt: '2026-02-08T23:57:00Z',
    updatedAt: '2026-02-08T23:57:00Z',
  },
  {
    id: 'seed-nyt-chipotle-honey-chicken-tacos',
    title: 'Chipotle-Honey Chicken Tacos',
    description:
      'Sarah DiGregorio\'s 5-star NYT hit (6,323 ratings). Smoky chipotles in adobo + honey = glossy, spicy-sweet shredded chicken. Pressure cooker does the heavy lifting in 13 minutes. Pickled onions take it over the top.',
    ingredients: [
      '1½ lbs boneless, skinless chicken thighs',
      '1–4 canned chipotles in adobo, finely chopped, plus 2 tbsp adobo sauce',
      '3 tbsp honey',
      '1 tsp onion powder',
      '1 tsp garlic powder',
      '1 tsp kosher salt (Diamond Crystal), plus more to taste',
      '½ tsp ground cumin',
      '1 (15-oz) can black beans, rinsed and drained',
      '1 lime, juiced',
      'Siete cassava tortillas, warmed',
      'Pickled red onion, for serving (see tip below)',
      'Sliced or cubed avocado, for serving',
    ],
    instructions: [
      'Combine chicken, chipotles + adobo sauce, honey, onion powder, garlic powder, salt, and cumin in your Instant Pot. Stir well. Cover, set steam valve to sealed. Cook on high pressure for 13 minutes.',
      'Let pressure release naturally for 5 minutes, then manually release the rest. Open the lid.',
      'Remove chicken to a bowl or cutting board with tongs. Shred with two forks.',
      'Optional: to reduce the sauce, set to Sauté and simmer 5 minutes for a thicker, glossier coating. Return shredded chicken to the pot.',
      'Stir in black beans and a squeeze of lime juice. Set to Sauté and warm through, 2–3 minutes. Taste — add more salt or lime juice as needed.',
      'Warm your Siete cassava tortillas. Serve chicken and beans in tortillas, topped with pickled onions and avocado.',
      'TIP — Quick pickled onions: Thinly slice a red onion into a heat-proof container. Boil 1½ cups cider or white vinegar with 3 heaping spoonfuls of sugar and a big pinch of salt. Optional: red pepper flakes, bay leaf, dried oregano. Pour hot vinegar over onions, let cool. Ready immediately. Keeps 2 weeks in the fridge.',
    ],
    photoUrl: '/recipes/chipotle-honey-chicken-tacos.jpg',
    servings: '4',
    cookTime: '25 min',
    prepTime: '10 min',
    totalTimeMinutes: 35,
    sourceUrl: 'https://cooking.nytimes.com/recipes/1020434-pressure-cooker-chipotle-honey-chicken-tacos',
    videoUrl: '',
    proteinType: 'chicken',
    cookingMethod: 'instant-pot',
    nutrition: {
      calories: 600,
      protein: 43,
      carbs: 50,
      fat: 25,
      perServing: true,
    },
    createdAt: '2026-02-09T00:11:00Z',
    updatedAt: '2026-02-09T00:11:00Z',
  },
  {
    id: 'seed-nyt-beef-chili',
    title: 'Classic Beef Chili (Pressure Cooker)',
    description:
      'Melissa Clark\'s 5-star NYT classic (3,141 ratings). Gently spiced, deeply satisfying. Brown the beef properly, 8 minutes on high pressure, done. Use 80% lean for max flavor. Freezes like a dream.',
    ingredients: [
      '2 tbsp olive oil',
      '1 lb ground beef (80/20 recommended)',
      '2 tsp kosher salt (Diamond Crystal), plus more to taste',
      '1 large onion, diced',
      '1 green bell pepper, seeded and diced',
      '1 jalapeño, seeded or not, diced',
      '4 cloves garlic, finely grated or minced',
      '2 tbsp chili powder',
      '1 tbsp tomato paste',
      '½ tsp ground cumin',
      '1 tsp dried oregano',
      '1 (13.5-oz) can diced tomatoes',
      '2 (15-oz) cans pinto or kidney beans, drained and rinsed',
      '⅓ cup chopped cilantro leaves and tender stems',
      'Fresh lime juice, to taste',
      'Sour cream, for serving',
      'Cubed avocado, for serving (optional)',
      'Pickled jalapeño, for serving (optional)',
    ],
    instructions: [
      'Set pressure cooker to Sauté on high. Heat olive oil, add beef, spread over the bottom and let it brown without stirring for 7 minutes. Stir and sauté 1 more minute. Transfer beef to a plate with a slotted spoon. Season with 1 tsp salt.',
      'Stir in onion, bell pepper, jalapeño, garlic, and ½ tsp salt. Cook until softened, about 5 minutes.',
      'Stir in chili powder, tomato paste, and cumin. Cook until fragrant, about 1 minute.',
      'Add beef and any plate juices back in, plus oregano, diced tomatoes, beans, and remaining ½ tsp salt. Stir to combine.',
      'Cover, seal, and cook on high pressure for 8 minutes. Let pressure release naturally.',
      'Stir in cilantro and a squeeze or two of lime juice. Taste and adjust seasoning.',
      'Serve with sour cream, avocado, and pickled jalapeño.',
      'TIP: If you get a burn signal, add ½ cup water, beer, or stock to the pot. Leftovers freeze beautifully.',
    ],
    photoUrl: '/recipes/beef-chili.jpg',
    servings: '5',
    cookTime: '45 min',
    prepTime: '15 min',
    totalTimeMinutes: 60,
    sourceUrl: 'https://cooking.nytimes.com/recipes/1019865-pressure-cooker-classic-beef-chili',
    videoUrl: '',
    proteinType: 'beef',
    cookingMethod: 'instant-pot',
    nutrition: {
      calories: 480,
      protein: 27,
      carbs: 30,
      fat: 27,
      perServing: true,
    },
    createdAt: '2026-02-09T00:12:00Z',
    updatedAt: '2026-02-09T00:12:00Z',
  },
];
