import { Recipe } from './types';

export const seedRecipes: Recipe[] = [
  {
    id: 'seed-1',
    title: 'Cacio e Pepe',
    description:
      'The Roman classic in its purest form — just pasta, pecorino, and black pepper. Deceptively simple, impossibly satisfying.',
    ingredients: [
      '1 lb tonnarelli or spaghetti',
      '2 cups finely grated Pecorino Romano',
      '2 tbsp freshly cracked black pepper (coarse)',
      'Kosher salt for pasta water',
    ],
    instructions: [
      'Bring a pot of well-salted water to boil. Use less water than usual — you want it starchy.',
      'Toast the cracked black pepper in a large dry skillet over medium heat for 1-2 minutes until fragrant. Add 1 cup of pasta water and let it simmer.',
      'Cook pasta 1 minute shy of al dente. Reserve 2 cups of starchy pasta water before draining.',
      'Combine Pecorino in a bowl with ½ cup of warm (not hot!) pasta water. Stir into a thick paste.',
      'Transfer pasta to the pepper skillet with tongs. Add ½ cup more pasta water.',
      'Remove from heat. Add the Pecorino paste in three additions, tossing vigorously each time.',
      'Add splashes of pasta water as needed — you want glossy, coating consistency.',
      'Serve immediately on warm plates. Top with more Pecorino and pepper.',
    ],
    photoUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80',
    servings: '4',
    cookTime: '15 min',
    prepTime: '10 min',
    totalTimeMinutes: 25,
    sourceUrl: '',
    videoUrl: '',
    proteinType: 'none',
    cookingMethod: 'stovetop',
    nutrition: {
      calories: 520,
      protein: 22,
      carbs: 65,
      fat: 18,
      perServing: true,
    },
    createdAt: '2025-02-01T18:30:00Z',
    updatedAt: '2025-02-01T18:30:00Z',
  },
  {
    id: 'seed-2',
    title: 'Honey Walnut Shrimp',
    description:
      "Crispy, creamy, sweet — the Chinese-American takeout classic that's actually worth making at home. Candied walnuts, tempura-battered shrimp, and that iconic condensed milk sauce.",
    ingredients: [
      '1 lb large shrimp, peeled and deveined',
      '1 cup walnuts',
      '½ cup sugar (for candying walnuts)',
      '¼ cup water (for candying walnuts)',
      '¾ cup cornstarch',
      '2 egg whites',
      '¼ cup mayonnaise (Kewpie preferred)',
      '2 tbsp sweetened condensed milk',
      '1 tbsp honey',
      '1 tbsp fresh lemon juice',
      'Vegetable oil for frying',
      'Pinch of salt',
    ],
    instructions: [
      'Candy the walnuts: combine sugar and ¼ cup water in a small saucepan. Bring to a boil, add walnuts, simmer 5 minutes. Spread on parchment to cool.',
      'Make the sauce: whisk together Kewpie mayo, condensed milk, honey, and lemon juice.',
      'Pat shrimp dry. Whisk egg whites until slightly frothy. Toss shrimp in egg whites, then dredge in cornstarch.',
      'Heat 2 inches of oil to 350°F. Fry shrimp in batches for 2-3 minutes until golden. Drain on wire rack.',
      'Toss hot shrimp with the sauce until evenly coated.',
      'Plate on shredded lettuce. Scatter candied walnuts on top.',
      'Serve immediately — the shrimp lose their crunch fast.',
    ],
    photoUrl: 'https://images.unsplash.com/photo-1625943553852-781c6dd46faa?w=800&q=80',
    servings: '4',
    cookTime: '25 min',
    prepTime: '20 min',
    totalTimeMinutes: 45,
    sourceUrl: '',
    videoUrl: '',
    proteinType: 'seafood',
    cookingMethod: 'stovetop',
    nutrition: {
      calories: 480,
      protein: 28,
      carbs: 42,
      fat: 22,
      perServing: true,
    },
    createdAt: '2025-04-05T19:00:00Z',
    updatedAt: '2025-04-05T19:00:00Z',
  },
  {
    id: 'seed-3',
    title: 'Crispy Air Fryer Chicken Thighs',
    description:
      'Insanely crispy skin, juicy meat, minimal effort. The air fryer was made for chicken thighs. Season simply and let the hot air do its thing.',
    ingredients: [
      '6 bone-in, skin-on chicken thighs',
      '1 tbsp olive oil',
      '1 tsp garlic powder',
      '1 tsp smoked paprika',
      '½ tsp onion powder',
      '½ tsp dried thyme',
      'Salt and pepper to taste',
      'Lemon wedges for serving',
    ],
    instructions: [
      'Pat chicken thighs completely dry with paper towels. This is crucial for crispy skin.',
      'Rub with olive oil. Mix garlic powder, smoked paprika, onion powder, thyme, salt, and pepper. Season all sides generously.',
      'Preheat air fryer to 400°F for 3 minutes.',
      'Place thighs skin-side down in the air fryer basket. Don\'t crowd — cook in batches if needed.',
      'Cook for 10 minutes skin-side down.',
      'Flip to skin-side up. Cook another 12-15 minutes until internal temp hits 185°F and skin is deeply golden and crispy.',
      'Rest for 5 minutes before serving. Squeeze lemon over the top.',
    ],
    photoUrl: 'https://images.unsplash.com/photo-1598103442097-8b74f0969e17?w=800&q=80',
    servings: '4',
    cookTime: '25 min',
    prepTime: '10 min',
    totalTimeMinutes: 35,
    sourceUrl: '',
    videoUrl: '',
    proteinType: 'chicken',
    cookingMethod: 'air-fryer',
    nutrition: {
      calories: 340,
      protein: 32,
      carbs: 1,
      fat: 22,
      perServing: true,
    },
    createdAt: '2025-06-15T12:00:00Z',
    updatedAt: '2025-06-15T12:00:00Z',
  },
  {
    id: 'seed-4',
    title: 'Korean Beef Bulgogi Bowl',
    description:
      'Sweet, savory, slightly smoky thinly-sliced beef over steamed rice. The marinade is everything — soy, pear, sesame, and gochugaru.',
    ingredients: [
      '1.5 lbs ribeye or sirloin, thinly sliced',
      '1 Asian pear, grated (or ½ cup pear juice)',
      '¼ cup soy sauce',
      '2 tbsp sesame oil',
      '2 tbsp brown sugar',
      '4 cloves garlic, minced',
      '1 tbsp gochugaru (Korean red pepper flakes)',
      '1 tbsp rice vinegar',
      '1 tsp freshly grated ginger',
      '2 green onions, sliced',
      '1 tbsp toasted sesame seeds',
      'Steamed rice for serving',
      'Kimchi for serving (optional)',
    ],
    instructions: [
      'Mix grated pear, soy sauce, sesame oil, brown sugar, garlic, gochugaru, rice vinegar, and ginger in a large bowl.',
      'Add sliced beef and toss to coat. Marinate for at least 30 minutes (up to overnight in the fridge).',
      'Heat a large skillet or grill pan over high heat until smoking hot.',
      'Cook beef in a single layer in batches — don\'t crowd the pan. 2-3 minutes per side for caramelized edges.',
      'Serve over steamed rice. Top with sliced green onions and sesame seeds.',
      'Add kimchi on the side if you have it.',
    ],
    photoUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80',
    servings: '4',
    cookTime: '15 min',
    prepTime: '40 min',
    totalTimeMinutes: 55,
    sourceUrl: '',
    videoUrl: '',
    proteinType: 'beef',
    cookingMethod: 'stovetop',
    nutrition: {
      calories: 520,
      protein: 38,
      carbs: 45,
      fat: 20,
      perServing: true,
    },
    createdAt: '2025-07-20T18:00:00Z',
    updatedAt: '2025-07-20T18:00:00Z',
  },
];
